version: '3.3'

services:
  eco:
    container_name: eco-api
    image: ecr_repo_uri
    volumes:
      - ./:/django-docker
      - static:/django-docker/static
      - media:/django-docker/Storage
    env_file:
      - ./env/db.env
    ports:
      - "80:80"
    restart: always
      
  # api_nginx:
  #   container_name: eco-nginx
  #   build:
  #     context: ./api_nginx
  #   volumes:
  #     - static:/static
  #     - media:/Storage
  #   restart: always
  #   ports:
  #     - 9000:9000
  #   depends_on:
  #     - eco
  #     - db
  db:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - ./env/pg.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  static:
  media:
  postgres_data: